name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{secrets.APTIBLE_ROBOT_USERNAME}}
          password: ${{secrets.APTIBLE_ROBOOT_PASSWORD}}
          app: "deploy-action-demo"
          environment: "chaos"
          docker_img: "aptible/github-action-demo"
