name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          - aptible_email: ${{secrets.APTIBLE_ROBOT_USERNAME}}
          - aptible_password: ${{secrets.APTIBLE_ROBOOT_PASSWORD}}
          - aptible_app: "deploy-action-demo"
          - aptible_environment: "production"
