name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image_name: aptible/github-action-demo
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Publish to Registry
        id: publish_image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ env.image_name }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    outputs:
      image: ${{ env.image_name }}:${{ steps.publish_image.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@fix-versioned-release
        with:
          type: docker
          username: ${{ vars.APTIBLE_ROBOT_USERNAME }}
          password: ${{ secrets.APTIBLE_ROBOOT_PASSWORD }}
          app: ${{ github.event_name == 'pull_request' && 'deploy-action-demo-staging' || 'deploy-action-demo' }}
          environment: public-demos
          docker_img: ${{ needs.build.outputs.image }}
          config_variables: FORCE_SSL=true 
